version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: dependabot
      include: scope
  - package-ecosystem: npm
    directory: /audit-test-tools
    schedule:
      interval: daily
    commit-message:
      prefix: dependabot
      include: scope
  - package-ecosystem: npm
    directory: /dev-tools
    schedule:
      interval: daily
    commit-message:
      prefix: dependabot
      include: scope
