version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: dependabot
      include: scope
    ignore:
      - dependency-name: '*'
        update-types:
          - version-update:semver-major
      - dependency-name: '@aws-sdk/*'
  - package-ecosystem: npm
    directory: /audit-test-tools
    schedule:
      interval: daily
    commit-message:
      prefix: dependabot
      include: scope
    ignore:
      - dependency-name: '*'
        update-types:
          - version-update:semver-major
      - dependency-name: '@aws-sdk/*'
  - package-ecosystem: npm
    directory: /dev-tools
    schedule:
      interval: daily
    commit-message:
      prefix: dependabot
      include: scope
    ignore:
      - dependency-name: '*'
        update-types:
          - version-update:semver-major
      - dependency-name: '@aws-sdk/*'
