AWSTemplateFormatVersion: '2010-09-09'
Description: Static infrastructure for Shared Signal Framework
Transform: AWS::Serverless-2016-10-31

Parameters:
  Environment:
    Description: The environment type
    Type: String
    AllowedValues:
      - dev
      - build
      - staging
      - integration
      - production

Conditions:
  IsProduction: !Equals [!Ref Environment, 'production']
  NotTestEnvironment:
    !Or [
      !Equals [!Ref Environment, production],
      !Equals [!Ref Environment, integration]
    ]

Resources:
  ####################
  # DynamoDB Resources
  ####################

  UserConfigTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: !Sub ${AWS::StackName}-user-config
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: !If [NotTestEnvironment, false, true]
      AttributeDefinitions:
        - AttributeName: client_id
          AttributeType: S
      KeySchema:
        - AttributeName: client_id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
        KMSMasterKeyId: '{{resolve:ssm:DatabaseKmsKeyArn}}'

  ####################
  # Cognito Resources
  ####################

  SSFUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub ${AWS::StackName}-ssf-user-pool

  SSFUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      UserPoolId: !Ref SSFUserPool
      Domain: !Sub di-txma-${AWS::StackName}-${Environment}-ssf-auth

  ################
  # SSM Parameters
  ################

  UserConfigTableArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: UserConfigTableArn
      Type: String
      Value: !GetAtt UserConfigTable.Arn

  UserConfigTableNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: UserConfigTableName
      Type: String
      Value: !Ref UserConfigTable

  SSFUserPoolIdParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: SSFUserPoolId
      Type: String
      Value: !Ref SSFUserPool

  SSFUserPoolArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: SSFUserPoolArn
      Type: String
      Value: !GetAtt SSFUserPool.Arn

  PreGeneratedCognitoTestUsers:
  Type: AWS::SecretsManager::Secret
  Properties:
    Description: 'A set of cognito users that can be used to authenticate against shared signals API Gateway'
    KmsKeyId: '{{resolve:ssm:SecretsKmsKeyArn}}'
    Name: APIGatewayTestUsers

Outputs:
  SSFUserPoolId:
    Description: 'user pool id for cognito'
    Value: !Ref SSFUserPool
  UserConfigTableName:
    Description: 'table name for user config table'
    Value: !Ref UserConfigTable
  PreGeneratedCognitoUsersSecretARN:
    Description: 'ARN of secret that stores test cognito users for API gateway testing'
    Value: !Ref PreGeneratedCognitoTestUsers
