packageExtensions:
  '@jest/core@*':
    peerDependencies:
      ts-node: '*'
    peerDependenciesMeta:
      ts-node:
        optional: true
  jest-cli@*:
    peerDependencies:
      ts-node: '*'
    peerDependenciesMeta:
      '@types/node':
        optional: true
  jest@*:
    peerDependencies:
      ts-node: '*'
    peerDependenciesMeta:
      ts-node:
        optional: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-3.4.1.cjs
