AWSTemplateFormatVersion: '2010-09-09'
Description: Static infrastructure for Audit system
Transform: AWS::Serverless-2016-10-31

Parameters:
  Environment:
    Description: The environment type
    Type: String
    AllowedValues:
      - dev
      - build
      - staging
      - integration
      - production
  AuditAccountNumber:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: 'txma-audit-account-number'

Outputs:
  EncryptionGeneratorKmsKeyArn:
    Description: This is the ARN for the KMS key used for encryption
    Value: !GetAtt EncryptionGeneratorKmsKey.Arn

Resources:
  ###################
  # Start: KMS Keys #
  ###################

  EncryptionGeneratorKmsKey:
    Type: AWS::KMS::Key
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Metadata:
      checkov:
        skip:
          - id: CKV_AWS_7
            comment: Automatic key rotation is not supported for multi-region keys
    Properties:
      MultiRegion: true
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          - Sid: Enable Root access
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action:
              - kms:*
            Resource: '*'
          - Sid: Allow Lambda execution role access
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AuditAccountNumber}:root'
            Action:
              - kms:Encrypt
              - kms:Decrypt
              - kms:GenerateDataKey
            Resource: '*'
            Condition:
              StringLike:
                aws:PrincipalArn:
                  - !Sub 'arn:aws:iam::${AuditAccountNumber}:role/*-s3-copy-and-encrypt-role'
                  - !Sub 'arn:aws:iam::${AuditAccountNumber}:role/*-decrypt-and-copy-role'
                  - !Sub 'arn:aws:iam::${AuditAccountNumber}:role/*-s3-key-rotation-role'

  EncryptionGeneratorKmsKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub alias/${AWS::StackName}/${Environment}/encryption-generator-kms-key
      TargetKeyId: !Ref EncryptionGeneratorKmsKey

  #################
  # End: KMS Keys #
  #################
