AWSTemplateFormatVersion: '2010-09-09'
Description: Creates the necessary DNS records, certificates and domain names for the query results account
Parameters:
  Environment:
    Description: The environment type
    Type: String
    AllowedValues:
      - build
      - staging
      - integration
      - production

Conditions:
  IsProduction: !Equals [!Ref Environment, production]
  IsBuild: !Equals [!Ref Environment, build]

Resources:
  ZendeskWebhookApiCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName:
        !If [
          IsProduction,
          zendesk.transaction.account.gov.uk,
          !Sub 'zendesk.transaction.${Environment}.account.gov.uk'
        ]
      DomainValidationOptions:
        - DomainName:
            !If [
              IsProduction,
              zendesk.transaction.account.gov.uk,
              !Sub 'zendesk.transaction.${Environment}.account.gov.uk'
            ]
          HostedZoneId: !ImportValue ZendeskWebhookApiPublicHostedZoneId
      ValidationMethod: DNS

  ZendeskWebhookApiDomainName:
    Type: AWS::ApiGateway::DomainName
    Properties:
      DomainName:
        !If [
          IsProduction,
          zendesk.transaction.account.gov.uk,
          !Sub 'zendesk.transaction.${Environment}.account.gov.uk'
        ]
      EndpointConfiguration:
        Types:
          - REGIONAL
      RegionalCertificateArn: !Ref ZendeskWebhookApiCertificate
      SecurityPolicy: TLS_1_2

  ZendeskWebhookApiAliasRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        DNSName: !GetAtt ZendeskWebhookApiDomainName.RegionalDomainName
        EvaluateTargetHealth: false
        HostedZoneId: !GetAtt ZendeskWebhookApiDomainName.RegionalHostedZoneId
      HostedZoneId: !ImportValue ZendeskWebhookApiPublicHostedZoneId
      Name: !Ref ZendeskWebhookApiDomainName
      Type: A

  ZendeskWebhookApiDomainNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: ZendeskWebhookApiDomainName
      Type: String
      Value: !Ref ZendeskWebhookApiDomainName

  # Mock server records

  MockServerCertificate:
    Type: AWS::CertificateManager::Certificate
    Condition: IsBuild
    Properties:
      DomainName: !Sub 'mockserver.transaction.${Environment}.account.gov.uk'
      DomainValidationOptions:
        - DomainName: !Sub 'mockserver.transaction.${Environment}.account.gov.uk'
          HostedZoneId: !ImportValue MockServerPublicHostedZoneId
      ValidationMethod: DNS

  MockServerDomainName:
    Type: AWS::ApiGateway::DomainName
    Properties:
      DomainName: !Sub 'mockserver.transaction.${Environment}.account.gov.uk'
      EndpointConfiguration:
        Types:
          - REGIONAL
      RegionalCertificateArn: !Ref MockServerCertificate
      SecurityPolicy: TLS_1_2

  MockServerCertificateAliasRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        DNSName: !GetAtt MockServerDomainName.RegionalDomainName
        EvaluateTargetHealth: false
        HostedZoneId: !GetAtt MockServerDomainName.RegionalHostedZoneId
      HostedZoneId: !ImportValue MockServerPublicHostedZoneId
      Name: !Ref MockServerDomainName
      Type: A

  MockServerDomainNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: MockServerDomainName
      Type: String
      Value: !Ref MockServerDomainName
