AWSTemplateFormatVersion: '2010-09-09'
Description: Audit accoun test tool infrastructure
Transform: AWS::Serverless-2016-10-31

Parameters:
  CodeSigningConfigArn:
    Description: The ARN of the Code Signing Config to use, provided by the deployment pipeline
    Type: String
    Default: none
  Environment:
    Description: The environment type
    Type: String
    AllowedValues:
      - dev
      - build
      - staging
  PermissionsBoundary:
    Description: The ARN of the permissions boundary to apply to any role created by the template
    Type: String
    Default: none

Conditions:
  UseCodeSigning: !Not [!Equals [!Ref CodeSigningConfigArn, none]]
  UsePermissionsBoundary: !Not [!Equals [!Ref PermissionsBoundary, none]]

Globals:
  Function:
    CodeSigningConfigArn:
      !If [UseCodeSigning, !Ref CodeSigningConfigArn, !Ref AWS::NoValue]
    CodeUri: dist/
    Environment:
      Variables:
        NODE_OPTIONS: --enable-source-maps
    PermissionsBoundary:
      !If [UsePermissionsBoundary, !Ref PermissionsBoundary, !Ref AWS::NoValue]
    ReservedConcurrentExecutions: 10
    Runtime: nodejs16.x
    Timeout: 30

Resources:
  WriteTestDataToAthenaBucketFunction:
    #checkov:skip=CKV_AWS_115:Defined in Globals section
    #checkov:skip=CKV_AWS_116:The SQS queue itself will be responsible for its own DLQ
    #checkov:skip=CKV_AWS_117:VPC not required
    Type: AWS::Serverless::Function
    Properties:
      Handler: writeTestDataToAthenaBucket.handler
      Role: !GetAtt WriteTestDataToAthenaBucketFunctionRole.Arn
      Environment:
        Variables:
          ATHENA_OUTPUT_BUCKET_NAME: '{{resolve:ssm:AthenaQueryOutputBucketName}}'
          QUERY_COMPLETED_QUEUE_URL: '{{resolve:ssm:QueryCompletedQueueUrl}}'
      FunctionName: !Sub ${AWS::StackName}-write-test-data-to-athena-bucket
      KmsKeyArn: '{{resolve:ssm:LambdaKmsKeyArn}}'
      Events:
        QRIntegrationTestsTrigggerEvent:
          Type: SQS
          Properties:
            Queue: !Sub 'arn:aws:sqs:${AWS::Region}:{{resolve:ssm:QueryResultsAccountNumber}}:txma-query-results-${Environment}-write-test-data-to-athena-bucket-queue'
            BatchSize: 1

  WriteTestDataToAthenaBucketFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AWS::StackName}-${Environment}-write-test-data-to-athena-bucket-role
      PermissionsBoundary:
        !If [
          UsePermissionsBoundary,
          !Ref PermissionsBoundary,
          !Ref AWS::NoValue
        ]
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AllowWriteTestDataToAthenaBucketActions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: Logs
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !GetAtt WriteTestDataToAthenaBucketLogs.Arn
              - Sid: AllowQRIntegrationsTestsTriggerQueueRead
                Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                Resource: !Sub 'arn:aws:sqs:${AWS::Region}:{{resolve:ssm:QueryResultsAccountNumber}}:txma-query-results-${Environment}-write-test-data-to-athena-bucket-queue'
              - Sid: DecryptKmsKeys
                Effect: Allow
                Action:
                  - kms:Decrypt
                Resource:
                  - '{{resolve:ssm:SecretsKmsKeyArn}}'
                  - !Sub 'arn:aws:kms:${AWS::Region}:{{resolve:ssm:QueryResultsAccountNumber}}:*'
              - Sid: AllowSqsSendToQueryCompletedQueue
                Effect: Allow
                Action:
                  - sqs:SendMessage
                Resource:
                  - '{{resolve:ssm:QueryCompletedQueueArn}}'
              - Sid: UseQueryCompletedQueueKmsKey
                Effect: Allow
                Action:
                  - kms:Decrypt
                  - kms:GenerateDataKey*
                  - kms:ReEncrypt*
                Resource:
                  - '{{resolve:ssm:QueryCompletedQueueKmsKeyArn}}'

  WriteTestDataToAthenaBucketLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      KmsKeyId: '{{resolve:ssm:LogsKmsKeyArn}}'
      LogGroupName: !Sub '/aws/lambda/${AWS::StackName}-write-test-data-to-athena-bucket'
      RetentionInDays: 30
