name: Package DNS records for Audit account

on:
  push:
    paths:
      - infrastructure/dns-records-audit/**
  workflow_dispatch: {}

env:
  AWS_REGION: eu-west-2

jobs:
  package:
    strategy:
      matrix:
        target: [AUDIT_BUILD]
        include:
          - target: AUDIT_BUILD
            ARTIFACT_BUCKET_NAME_SECRET: ARTIFACT_BUCKET_NAME_DNS_RECORDS_AUDIT_BUILD
            GH_ACTIONS_ROLE_ARN_SECRET: GH_ACTIONS_ROLE_ARN_DNS_RECORDS_AUDIT_BUILD
            SIGNING_PROFILE_SECRET: SIGNING_PROFILE_NAME_AUDIT_BUILD
    name: Package template
    if: github.ref == 'refs/heads/main'
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Setup Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@v2
      - name: Assume AWS role
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets[matrix.GH_ACTIONS_ROLE_ARN_SECRET] }}
      - name: Package SAM app
        uses: alphagov/di-devplatform-upload-action@v3
        with:
          artifact-bucket-name: ${{ secrets[matrix.ARTIFACT_BUCKET_NAME_SECRET] }}
          signing-profile-name: ${{ secrets[matrix.SIGNING_PROFILE_SECRET] }}
          template-file: infrastructure/dns-records-audit/template.yaml
          working-directory: '.'
