name: Package dev tools infrastructure

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - infrastructure/dev-tools/**
  push:
    branches:
      - main
    paths:
      - infrastructure/dev-tools/**
      - .node_modules/**
  workflow_dispatch: {}

env:
  AWS_REGION: eu-west-2

jobs:
  code-quality:
    if: ${{ github.event_name == 'pull_request' && github.event.pull_request.draft == false && github.actor != 'dependabot[bot]' }}
    permissions:
      contents: read
    uses: ./.github/workflows/code-quality-checkov.yaml
    with:
      template_path: infrastructure/dev-tools/template.yaml

  build:
    name: Build Lambda functions
    runs-on: ubuntu-latest
    timeout-minutes: 15
    defaults:
      run:
        working-directory: infrastructure/dev-tools
    steps:
      - name: Check out repository code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Node 24
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 24
          cache: npm
          cache-dependancy-path: package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: .

      - name: Run tests
        if: always()
        run: npm run test
      - name: Build Lambda functions
        if: always()
        run: npm run build
      - name: Upload build artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: dev-tools-sam-template
          path: |
            .git/
            infrastructure/dev-tools/dist/
            infrastructure/dev-tools/template.yaml
          retention-days: 7
          include-hidden-files: true

  package:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    strategy:
      matrix:
        include:
          - target: AUDIT_DEV
            ARTIFACT_BUCKET_NAME_SECRET: ARTIFACT_BUCKET_NAME_DEV_TOOLS_AUDIT_DEV
            GH_ACTIONS_ROLE_ARN_SECRET: GH_ACTIONS_ROLE_ARN_DEV_TOOLS_AUDIT_DEV
            SIGNING_PROFILE_SECRET: SIGNING_PROFILE_NAME_AUDIT_DEV
          - target: EVENT_PROCESSING_DEV
            ARTIFACT_BUCKET_NAME_SECRET: ARTIFACT_BUCKET_NAME_DEV_TOOLS_EVENT_PROCESSING_DEV
            GH_ACTIONS_ROLE_ARN_SECRET: GH_ACTIONS_ROLE_ARN_DEV_TOOLS_EVENT_PROCESSING_DEV
            SIGNING_PROFILE_SECRET: SIGNING_PROFILE_NAME_EVENT_PROCESSING_DEV
          - target: QUERY_RESULTS_DEV
            ARTIFACT_BUCKET_NAME_SECRET: ARTIFACT_BUCKET_NAME_DEV_TOOLS_QUERY_RESULTS_DEV
            GH_ACTIONS_ROLE_ARN_SECRET: GH_ACTIONS_ROLE_ARN_DEV_TOOLS_QUERY_RESULTS_DEV
            SIGNING_PROFILE_SECRET: SIGNING_PROFILE_NAME_QUERY_RESULTS_DEV
          - target: SHARED_SIGNALS_DEV
            ARTIFACT_BUCKET_NAME_SECRET: ARTIFACT_BUCKET_NAME_DEV_TOOLS_SHARED_SIGNALS_DEV
            GH_ACTIONS_ROLE_ARN_SECRET: GH_ACTIONS_ROLE_ARN_DEV_TOOLS_SHARED_SIGNALS_DEV
            SIGNING_PROFILE_SECRET: SIGNING_PROFILE_NAME_SHARED_SIGNALS_DEV
          - target: RP_EVENTS_DEV
            ARTIFACT_BUCKET_NAME_SECRET: ARTIFACT_BUCKET_NAME_DEV_TOOLS_RP_EVENTS_DEV
            GH_ACTIONS_ROLE_ARN_SECRET: GH_ACTIONS_ROLE_ARN_DEV_TOOLS_RP_EVENTS_DEV
            SIGNING_PROFILE_SECRET: SIGNING_PROFILE_NAME_RP_EVENTS_DEV
          - target: AUDIT_BUILD
            ARTIFACT_BUCKET_NAME_SECRET: ARTIFACT_BUCKET_NAME_DEV_TOOLS_AUDIT_BUILD
            GH_ACTIONS_ROLE_ARN_SECRET: GH_ACTIONS_ROLE_ARN_DEV_TOOLS_AUDIT_BUILD
            SIGNING_PROFILE_SECRET: SIGNING_PROFILE_NAME_AUDIT_BUILD
          - target: EVENT_PROCESSING_BUILD
            ARTIFACT_BUCKET_NAME_SECRET: ARTIFACT_BUCKET_NAME_DEV_TOOLS_EVENT_PROCESSING_BUILD
            GH_ACTIONS_ROLE_ARN_SECRET: GH_ACTIONS_ROLE_ARN_DEV_TOOLS_EVENT_PROCESSING_BUILD
            SIGNING_PROFILE_SECRET: SIGNING_PROFILE_NAME_EVENT_PROCESSING_BUILD
          - target: QUERY_RESULTS_BUILD
            ARTIFACT_BUCKET_NAME_SECRET: ARTIFACT_BUCKET_NAME_DEV_TOOLS_QUERY_RESULTS_BUILD
            GH_ACTIONS_ROLE_ARN_SECRET: GH_ACTIONS_ROLE_ARN_DEV_TOOLS_QUERY_RESULTS_BUILD
            SIGNING_PROFILE_SECRET: SIGNING_PROFILE_NAME_QUERY_RESULTS_BUILD
          - target: SHARED_SIGNALS_BUILD
            ARTIFACT_BUCKET_NAME_SECRET: ARTIFACT_BUCKET_NAME_DEV_TOOLS_SHARED_SIGNALS_BUILD
            GH_ACTIONS_ROLE_ARN_SECRET: GH_ACTIONS_ROLE_ARN_DEV_TOOLS_SHARED_SIGNALS_BUILD
            SIGNING_PROFILE_SECRET: SIGNING_PROFILE_NAME_SHARED_SIGNALS_BUILD
          - target: RP_EVENTS_BUILD
            ARTIFACT_BUCKET_NAME_SECRET: ARTIFACT_BUCKET_NAME_DEV_TOOLS_RP_EVENTS_BUILD
            GH_ACTIONS_ROLE_ARN_SECRET: GH_ACTIONS_ROLE_ARN_DEV_TOOLS_RP_EVENTS_BUILD
            SIGNING_PROFILE_SECRET: SIGNING_PROFILE_NAME_RP_EVENTS_BUILD
    name: Package template
    needs: [build]
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: dev-tools-sam-template
      - name: Setup Python 3.8
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.8'
      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@v2
      - name: Assume AWS role
        uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37 # v6.1.0
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets[matrix.GH_ACTIONS_ROLE_ARN_SECRET] }}
      - name: Package SAM app
        uses: govuk-one-login/devplatform-upload-action@5879c30205266ad61e8299a4fcea76364530c9c1 # v3.14.0
        with:
          artifact-bucket-name: ${{ secrets[matrix.ARTIFACT_BUCKET_NAME_SECRET]}}
          signing-profile-name: ${{ secrets[matrix.SIGNING_PROFILE_SECRET] }}
          template-file: infrastructure/dev-tools/template.yaml
          working-directory: '.'
