name: Package Relying Parties Event Processing infrastructure

on:
  push:
    paths:
      - infrastructure/rp-events/**
  workflow_dispatch: {}

env:
  AWS_REGION: eu-west-2

jobs:
  validate:
    name: Validate template
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infrastructure/rp-events
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@v2
      - name: Assume AWS Validate role
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.GH_ACTIONS_VALIDATE_ROLE_ARN_RP_EVENTS}}
      - name: Validate SAM template
        if: always()
        run: sam validate --lint
      - name: Run Checkov on SAM template
        if: always()
        uses: bridgecrewio/checkov-action@master
        with:
          file: infrastructure/rp-events/template.yaml
          quiet: true
          framework: cloudformation
      - name: Upload template artifact
        uses: actions/upload-artifact@v3
        with:
          name: rp-events-sam-template
          path: |
            infrastructure/rp-events/template.yaml

  package:
    strategy:
      matrix:
        include:
          - target: RP_EVENTS_DEV
            ARTIFACT_BUCKET_NAME_SECRET: ARTIFACT_BUCKET_NAME_RP_EVENTS_DEV
            GH_ACTIONS_ROLE_ARN_SECRET: GH_ACTIONS_ROLE_ARN_RP_EVENTS_DEV
            SIGNING_PROFILE_SECRET: SIGNING_PROFILE_NAME_RP_EVENTS_DEV
          - target: RP_EVENTS_BUILD
            ARTIFACT_BUCKET_NAME_SECRET: ARTIFACT_BUCKET_NAME_RP_EVENTS_BUILD
            GH_ACTIONS_ROLE_ARN_SECRET: GH_ACTIONS_ROLE_ARN_RP_EVENTS_BUILD
            SIGNING_PROFILE_SECRET: SIGNING_PROFILE_NAME_RP_EVENTS_BUILD
    name: Package template
    if: github.ref == 'refs/heads/main'
    needs: [validate]
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Download template artifact
        uses: actions/download-artifact@v3
        with:
          name: rp-events-sam-template
      - name: Setup Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@v2
      - name: Assume AWS role
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets[matrix.GH_ACTIONS_ROLE_ARN_SECRET] }}
      - name: Package SAM app
        uses: alphagov/di-devplatform-upload-action@v3
        with:
          artifact-bucket-name: ${{ secrets[matrix.ARTIFACT_BUCKET_NAME_SECRET] }}
          signing-profile-name: ${{ secrets[matrix.SIGNING_PROFILE_SECRET] }}
          working-directory: '.'
