name: Package event processing infrastructure

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - infrastructure/event-processing/**
  push:
    branches:
      - main
    paths:
      - infrastructure/event-processing/**
  workflow_dispatch: {}

env:
  AWS_REGION: eu-west-2

jobs:
  code-quality:
    if: ${{ github.event_name == 'pull_request' && github.event.pull_request.draft == false && github.actor != 'dependabot[bot]' }}
    permissions:
      contents: read
    uses: ./.github/workflows/code-quality-checkov.yaml
    with:
      template_path: infrastructure/event-processing/template.yaml

  package:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    strategy:
      matrix:
        include:
          - target: EVENT_PROCESSING_DEV
            ARTIFACT_BUCKET_NAME_SECRET: ARTIFACT_BUCKET_NAME_EP_EVENTS_DEV
            GH_ACTIONS_ROLE_ARN_SECRET: GH_ACTIONS_ROLE_ARN_EP_EVENTS_DEV
            SIGNING_PROFILE_SECRET: SIGNING_PROFILE_NAME_EP_EVENTS_DEV
          - target: EVENT_PROCESSING_BUILD
            ARTIFACT_BUCKET_NAME_SECRET: ARTIFACT_BUCKET_NAME_EP_EVENTS_BUILD
            GH_ACTIONS_ROLE_ARN_SECRET: GH_ACTIONS_ROLE_ARN_EP_EVENTS_BUILD
            SIGNING_PROFILE_SECRET: SIGNING_PROFILE_NAME_EP_EVENTS_BUILD
    name: Package template - ${{ matrix.target }}
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repository code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Setup Python 3.8
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: '3.8'
      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@v2
      - name: Assume AWS role
        uses: aws-actions/configure-aws-credentials@254c19bd240aabef8777f48595e9d2d7b972184b # v6.2.1
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets[matrix.GH_ACTIONS_ROLE_ARN_SECRET] }}
      - name: Package SAM app
        uses: govuk-one-login/devplatform-upload-action@64e46134b4108ebfa1cf2a64fee00782f8e2e8cf # v4.1.0
        with:
          artifact-bucket-name: ${{ secrets[matrix.ARTIFACT_BUCKET_NAME_SECRET]}}
          signing-profile-name: ${{ secrets[matrix.SIGNING_PROFILE_SECRET] }}
          template-file: infrastructure/event-processing/template.yaml
          working-directory: '.'
