name: Validate templates, linting and tests

on:
  pull_request:
    branches:
      - main

jobs:
  linting-and-tests:
    name: Run linting and tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Check out repository code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup Node 24
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24
          cache: npm
          cache-dependancy-path: package-lock.json

      - name: Install dependencies
        run: npm ci
      - name: Run linting
        run: npm run lint
      - name: Run tests (dev-tools)
        run: npm run --workspace=dev-tools test
      - name: Run tests (audit-test-tools)
        run: npm run --workspace=audit-test-tools test

  validate-templates:
    name: Validate SAM templates
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Check out repository code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup Python 3.8
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: '3.8'
      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@v2
      - name: Validate SAM templates
        run: ./scripts/validate-templates.sh
